apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - ../../base
labels:
  - pairs:
      env: dev
    includeSelectors: false
patches:
  - target:
      kind: Deployment
      name: demo
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
